const colors = {
  light: {
    text: "#1A1A1A",
    tint: "#D4006A",
    background: "#F8F4F0",
    foreground: "#1A1A1A",
    card: "#FFFFFF",
    cardForeground: "#1A1A1A",
    primary: "#D4006A",
    primaryForeground: "#FFFFFF",
    secondary: "#FFF4CC",
    secondaryForeground: "#8B6000",
    muted: "#F0EAE6",
    mutedForeground: "#8A7A75",
    accent: "#00B8B8",
    accentForeground: "#FFFFFF",
    olive: "#6B7C00",
    oliveForeground: "#FFFFFF",
    destructive: "#E53E3E",
    destructiveForeground: "#FFFFFF",
    border: "#E8E0DC",
    input: "#E8E0DC",
    success: "#6B7C00",
    successForeground: "#FFFFFF",
    warning: "#F5C518",
    warningForeground: "#1A1A1A",
    dark: "#1A1A1A",
    darkForeground: "#FFFFFF",
  },
  radius: 12,
};

export default colors;
